### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by VictorKimbi** [vmurin/react-native-azure-auth-sample#17]
Sorry But I couldn't reply to your response by mail some issues with files being large but below is the log and info.plist

LOG  [aa.redirect_uri.not_expected: Expected msauth.org.reactjs.native.example.AwesomeAuthProject://auth but got msauth.org.reactjs.native.example.awesomeauthproject://auth/#code=0.AQkAvBFqbZpG30ilSNPzU6wb6FhPtMySOP9An0tGOZGM-NEJAEo.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P_Ls3qXCs2hLLz_hB4lqSxR3pbfuPYCgD5iDvvxT88RF1HZN7WYLSwz_6KeePc6Cd3MXWO1gBPtJ42vdWK7Ir5OZgPBuyOaAqBVo2PB7wa2qsrHGL18_-jbTD7yggonhtiDRgLwDd1O22yKbt_1m9dkMTifzUrIAy7V4XygvEN_w3oCJFn8lpN_vWdcYlpQef-PryErpjDWT-6ZzUkSpnds7EXJPVuy5MBKncpqo534qoq1SXENzZmYykYreKCBJZLyZ2-dWFCefhrpt7LQFcOw5GQhKdf4Ihbt5ifXQgut8GaaPHw6Te29YwmgbCaRZIOmlgiLymE0hWzSQuZG7MDywuOsLUZQwl5KS3aUmXTt2UwY5vD9z5TZdPNJ9lV0bFySuZagT4-D3oSLH9ho_EHjkJsPg6rDsCNGv84eGqd9DqhuF0AC5PAXy3R20XnGcWWGLJ8ZtKqH-uVaLUqM5qwBSK0KKlQnzi_1jnTYlLGmOn1bhXimKAJGsuZ1zY-n7n0NP4HiKepMl-ybGcPNuw2wp_V-GittlMzEoXqGXSeqtogxfsHLVkGs5Mm_OrHkMczWLlNqh46AVDrscOSfMbN4h9ifKWDMsTshOoPBKa9HeAy6pniPGaZhY4HYmbGWuipxbNTKYuKJN4zefax2Mi5W3SZ24PSzahj7ehv_0YOwAfrFFGntDt3v89mCaqGDw87hYAlRJqf_KsMA4rYOjprajigqEBEEq-ZJM8unsbB4OVbKQBDOE0R8tAY51kr9DD_vZBUaidC3AFm1ODdkKFOBKFbxyc5Ocf5UKue9x9k7_odJ6SeymZUdedYw9vOfLkNs-6E7dHVI2bAH829bcwfyIRjVoNCLaN5gpR3q9GWf2aMq6b3q1KCDD2oT12KcI6EhNDFiNOsuTkNjX0Opxkbn9xcY2_Kb6zjLfH1TnPyZxP8FH_P03dyCJRSlSQQd330sDExFAd3TBI6MHsTIYP6V1juMYHAsJyUkl1LXFWajgrcmn2JUr0S2DoeUNAITr0Upc_yR3YmN&id_token

#info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>AwesomeAuthProject</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>None</string>
			<key>CFBundleURLName</key>
			<string>AzureAuth</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>org.reactjs.native.example.AwesomeAuthProject</string>
			</array>
		</dict>
	</array>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by vmurin** [comment]
Please compare the call-back URIs in Azure App registration with the one sent from you App:

`msauth.org.reactjs.native.example.awesomeauthproject://auth/`

especially the last slash (it should be present)
And caps and small letters - all should be small

**Comment by VictorKimbi** [comment]
Thanks so much the casing was the issue

**Comment by vmurin** [comment]
👍🏻🙏
