### ISSUE TITLE
is it possible to make custom login page for react-native application using Azure-ad 

### ISSUE THREAD

**Issue by sultan-arshi** [vmurin/react-native-azure-auth-sample#6]
Basically my requirement is to build the `custom login` page for authenticate user, where user will enter his user and password and we will make some call to Azure to authenticate, authorisation and then public profile with graph api.
i have seen your lib and demo application which uses a auth lib for authentication but i want custom login page
https://docs.microsoft.com/en-us/graph/tutorials/react-native
so, is it possible ?

**Comment by vmurin** [comment]
If you what you own page to provide username and password, then it is not possible for most secure `autorization_code ` grant implemented in [react-native-azure-auth](https://github.com/vmurin/react-native-azure-auth).

Theoretically you could use client_credentials grant, but it is not actually meant for interactive user login, but rather for backend services.

But any other _custom login page_  in sens of a page with login/logout buttons, social logins etc is possible and independent from authorization library implementation.
